// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type Task struct {
	ID            int64
	TaskCode      sql.NullString
	TaskNotes     sql.NullString
	StartDate     sql.NullTime
	CompletedDate sql.NullTime
}
